In [2]:
import os
import tensorflow as tf

In [1]:
x = tf.random_uniform([])
y = tf.random_uniform([])
out = tf.cond(tf.greater(x,y),lambda: x+y,lambda: x-y)
with tf.Session() as sess:
    print(sess.run(out))

NameError: name 'tf' is not defined

In [5]:
x = tf.random_uniform([],-1,1)
y = tf.random_uniform([],-1,1)
out = tf.case({tf.less(x,y):(lambda: x+y),tf.greater(x,y):(lambda: x-y)},default=(lambda: 0.0))
with tf.Session() as sess:
    print(sess.run(out))

-1.3138194


In [7]:
x = tf.constant([[0,-2,-1],[0,1,2]])
y = tf.zeros_like(x)
z = tf.equal(x,y)
with tf.Session() as sess:
    print(sess.run(z))

[[ True False False]
 [ True False False]]


In [11]:
x = tf.constant([29.05088806,  27.61298943,  31.19073486,  29.35532951,
    30.97266006,  26.67541885,  38.08450317,  20.74983215,
    34.94445419,  34.45999146,  29.06485367,  36.01657104,
    27.88236427,  20.56035233,  30.20379066,  29.51215172,
    33.71149445,  28.59134293,  36.05556488,  28.66994858])
where_ind = tf.where(tf.greater(x,30))
out = tf.gather(x,where_ind)
with tf.Session() as sess:
    print(sess.run(out))

[[31.190735]
 [30.97266 ]
 [38.084503]
 [34.944454]
 [34.45999 ]
 [36.01657 ]
 [30.20379 ]
 [33.711494]
 [36.055565]]


In [13]:
x = tf.diag(tf.range(1,7))
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(tf.matrix_determinant(tf.random_normal([10,10]))))

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]
582.2648


In [14]:
x = tf.constant([5,2,3,5,10,6,2,3,4,2,1,1,0,9])
y,idx = tf.unique(x)
with tf.Session() as sess:
    print(sess.run([y,idx]))

[array([ 5,  2,  3, 10,  6,  4,  1,  0,  9]), array([0, 1, 2, 0, 3, 4, 1, 2, 5, 1, 6, 6, 7, 8])]


In [21]:
x = tf.random_normal([300])
y = tf.random_normal([300])
z = tf.reduce_mean(x-y)
out = tf.cond(tf.less(z,0),lambda: tf.reduce_mean(tf.square(x-y)),lambda: tf.reduce_sum(tf.abs(x-y)))
with tf.Session() as sess:
    print(sess.run(out))

1.8121643
